version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    volumes:
      - ./api:/app
    environment:
      MIX_ENV: "dev"
    env_file:
      - ./api/.env
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  
  nginx:
    # image: nginx:latest
    build:
      context: ./front-v2
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"

  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./front-v2
  #   volumes:
  #     - /app/node_modules
  #     - ./front-v2:/app

volumes:
  pgdata:
